import logoNore from "./nore-logo.png";
import noreCepat from "./nore-cepat.png";
import noreLangganan from "./nore-langganan.png";
import noreLengkap from "./nore-lengkap.png";
import norePraktis from "./nore-praktis.png";
import noreTerjangkau from "./nore-terjangkau.png";
import antara from "./antara-logo.png";
import carfix from "./carfix-logo.png";
import east from "./east-logo.png";
import healthproject from "./healthproject-logo.png";
import polres from "./polres-logo.png";
import sanori from "./sanori-logo.png";
import vendorbeli from "./vendorbeli-logo.png";

export const LogoNore = logoNore;
export const NoreCepat = noreCepat;
export const NoreLangganan = noreLangganan;
export const NoreLengkap = noreLengkap;
export const NorePraktis = norePraktis;
export const NoreTerjangkau = noreTerjangkau;
export const AntaraLogo = antara;
export const CarfixLogo = carfix;
export const EastLogo = east;
export const HealthProjectLogo = healthproject;
export const PolresLogo = polres;
export const SanoriLogo = sanori;
export const VendorbeliLogo = vendorbeli;
